### ISSUE TITLE
Otcv2

### ISSUE THREAD

**Issue by miguel-leal** [acey1337/otc3updated#2]
Hi my lord its me again, I contact you because I compile with otcv2(by Extremeblackliu) but when try to inject game crash, isnt the .dll because try with another injector and works. Do you know how to fix that?

**Comment by acey1337** [comment]
You mean you downloaded the loaders files and replaced the otc3 in the miscs folder with otc2? The loader grabs the .dll from https://github.com/acey1337/otc3updated/raw/main/miscs/OTv3.dll every time the inject button is pressed so you have to create your own github page and upload all the files there. Then edit Form1.cs and change the .dll download link from mine to yours. You don't have to create a github page actually you could just upload it on a file hosting website and use the direct download link.

**Comment by miguel-leal** [comment]
Yes, I do that and I read the comments in form1 I change to my direct link download otcv2 and compiled sir. I am not iq=null just saying that was like a bug and can't fix that.

**Comment by acey1337** [comment]
> Yes, I do that and I read the comments in form1 I change to my direct link download otcv2 and compiled sir. I am not iq=null just saying that was like a bug and can't fix that.

Hmm I see. I'm pretty sure it's the manualmap injection method that this loader uses or something. I've tried to get it to work with Otc2 just now and it just crashed the game as well. I've tried it with Osiris and it did the same thing too. By the way, I'm sorry if what I said above made you feel iq=null haha I didn't know if you were doing everything correctly.

**Comment by miguel-leal** [comment]
no worries lord, Otcv2 works perfect with this manual map https://github.com/mdilai/Shtreeba

**Comment by miguel-leal** [comment]
tell me if works for you

**Comment by acey1337** [comment]
> tell me if works for you

Yup, it does. Nice injector lol.
